language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

before_script:
  - composer install
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/php-cs-fixer fix --dry-run --diff --level psr2 .

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - jamie.hannaford@rackspace.com